### ISSUE TITLE
Sensitive RPC URLs for Sepolia, Arbitrum Sepolia, and ZkSync Committed in foundry.toml 🚨

### ISSUE THREAD

**Issue by bala-Blockchian** [Cyfrin/foundry-cross-chain-rebase-token-cu#2]
#### Description:
It appears the `foundry.toml` file in the project has been committed with sensitive RPC URLs for Sepolia, Arbitrum Sepolia, and ZkSync. The following section includes these RPC URLs:

```toml
[profile.default]
rpc_endpoints = { 
    eth = "************************************************************************************", 
    arb = "************************************************************************************", 
    zksync = "*********************************************************************************"
}
```

#### Issue:
Including actual RPC URLs with potential API keys in the repository can expose sensitive information and lead to risks such as unauthorized access and excessive API usage.

#### Suggested Action:

1. Replace them with placeholders, such as:

   ```toml
   rpc_endpoints = { 
       eth = "<RPC for Sepolia>", 
       arb = "<RPC for Arbitrum Sepolia>", 
       zksync = "<RPC for ZkSync>"
   }
   ```

2. Immediately remove the API keys in your Alchemy dashboard to prevent misuse of the exposed URLs.
